version: "3.8"

services:
  app:
    build:
      context: ./php-docker
      dockerfile: Dockerfile
    image: php_demo
    container_name: php_demo
    ports:
      - "8088:80" # "8080:80" - if you want to use the port 80
    volumes:
      # Mount source-code for development
      - ./php-docker/src:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway
  db:
    image: mysql:8
    container_name: php_demo_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./php-docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpmvc
      MYSQL_USER: phpmvc
      MYSQL_PASSWORD: phpmvc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '9080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
#Volumes
volumes:
  mysql-data:
    driver: local
