version: "3.6"

services:
  nginx_default:
    container_name: nginx_default
    image: nginx:1.23.1-alpine
    ports:
      - 9010:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
      - ../logs/nginx:/var/log/nginx
    links:
      - php_default
  php_default:
    container_name: php_default
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ../logs/php:/var/log
